(define (multiple-dwelling)
    (let ((fletcher (amb 2 3 4))
          (cooper (amb 2 3 4 5)))
        (require (> (abs (- fletcher cooper)) 1))
        (let ((miller (amb 1 2 3 4 5)))
            (require (> (miller cooper) 1))
            (let ((smith (amb 1 2 3 4 5)))
                (require (> (abs (- smith fletcher)) 1))
                (let ((baker (amb 1 2 3 4)))
                    (require
                        (distinct? (list baker cooper fletcher miller smith)))
                    (list
                        (list 'baker baker)
                        (list 'cooper cooper)
                        (list 'fletcher fletcher)
                        (list 'miller miller)
                        (list 'smith smith)))))))