(load "Chap2\\example\\exa2.2.4-painter.scm")
(load "Chap2\\exercise\\exe2.48-segment.scm")
(load "Chap2\\exercise\\exe2.46-vector.scm")

; a)
(define (painter-a frame)
    ((segment->painter (list (make-segment (make-vect 0 0) (make-vect 0 1))
                             (make-segment (make-vect 0 1) (make-vect 1 1))
                             (make-segment (make-vect 1 1) (make-vect 1 0))
                             (make-segment (make-vect 1 0) (make-vect 0 0))))
     frame))

; b)
(define (painter-b frame)
    ((segment->painter (list (make-segment (make-vect 0 0) (make-vect 1 1))
                             (make-segment (make-vect 0 1) (make-vect 1 0))))
     frame))

; c)
(define (painter-c frame)
    ((segment->painter (list (make-segment (make-vect 0 0.5) (make-vect 0.5 1))
                             (make-segment (make-vect 0.5 1) (make-vect 1 0.5))
                             (make-segment (make-vect 1 0.5) (make-vect 0.5 0))
                             (make-segment (make-vect 0.5 0) (make-vect 0 0.5))))
     frame))